name: tripyproject
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.2
  google_maps_flutter_web: ^0.5.4+3
  google_maps_cluster_manager_2: ^3.1.0
  geolocator: ^7.0.3
  http: ^0.13.3
  carousel_slider: ^4.2.1
  flutter_bloc: ^7.0.0
  provider: ^6.1.2
  loading_animation_widget: ^1.2.1
  mockito: ^5.0.14
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

